

services:
  postgres:
    image: postgres:15-alpine
    container_name: saving_ai_db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: saving_ai_dev
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-q", "-h", "localhost", "-p", "5432"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: saving_ai_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    
volumes:
  postgres_data: