services:
  posetgres:
    image: timescale/timescaledb:latest-pg16
    container_name: saving_ai_db
    environment:
      POSTGRES_DB: saving_ai_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: