<<<<<<< HEAD
services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: saving_ai_db
    environment:
      POSTGRES_DB: saving_ai_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    container_name: saving_ai_web
    ports:
      - "8000:8000"
    environment: 
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/saving_ai_dev
    depends_on:
      - postgres
    volumes: 
      - ./src:/app/src
    restart: unless-stopped 
    env_file: .env

volumes:
=======
services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: saving_ai_db
    environment:
      POSTGRES_DB: saving_ai_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    container_name: saving_ai_web
    ports:
      - "8000:8000"
    environment: 
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/saving_ai_dev
    depends_on:
      - postgres
    volumes: 
      - ./src:/app/src
    restart: unless-stopped 
    env_file: .env

volumes:
>>>>>>> 6563e49b59a03e0d73e2c4d2cec9abdc482d5ba5
  postgres_data: